title: Learning Notes
description: Explaining what I learn to understand it better
theme: jekyll-theme-minima

minima:
  skin: dark

markdown: kramdown

kramdown:
  math_engine: katex

plugins:
  - jekyll-feed