title: Learning Notes
description: Explaining what I learn to understand it better
theme: minima

minima:
  skin: dark

markdown: kramdown
header_pages: []

kramdown:
  math_engine: katex

plugins:
  - jekyll-feed